# ---------------------------------------------------------------
# Layout
# ---------------------------------------------------------------
divisionLine: true
articleImgInCenter: true
showTags: true
showCategories: true
toTop:
  use: ture
  icon: fa-pagelines
catalogBtn:
  use: true
  icon: fa-list-ul
excerpt: 100
footer: true
pages: 
  archives:
    link: "/archives"
    icon: "fa fa-file-text-o"
color:
  deactive: '#37474f'
  active: '#006064'  


# ---------------------------------------------------------------
# Blog Info
# ---------------------------------------------------------------
# If your article have tags, it will also be contained in the article html page's head.
# For a single article, you can add description in it's front-matter，than this article has it's own html description.
# Otherwise it's html description will only contain your site description.(hexo/_config.yml, #site, description)
# Description loading order: page description->page excerpt->blog description. When one of them was loaded, all of the rest will not be loaded.
head:
  keywords: 


# ---------------------------------------------------------------
# Author Info
# ---------------------------------------------------------------
info:
  slogan: "Nice to Meet you"
  avatarCard: false
img:
  # eg. site_logo: "/avatar.png"
  site_logo: '/favicon-leetcode.png'
  avatar: '/favicon-leetcode.png'
sns:
# eg.
email:
  link: "mailto:ladyrick@qq.com"
  icon: fa-envelope-o
github:
  link: "https://github.com/ladyrick"
  icon: fa fa-github


# ---------------------------------------------------------------
# Widget
# ---------------------------------------------------------------
# Now just for google_analytics(use: google_analytics, site_id: your tracking_id)
analytics:
    use: false
    site_id:
     
# Comment
# You can use disqus(use: disqus,shortname: your disqus shortname) or livere(use: livere, livereuid: your livereuid)
comment:
  use: 
  shortname: 
  livereuid: 