language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run index
- npx hexo generate
after_script:
- cd public
- git init
- git config user.name "ladyrick"
- git config user.email "ladyrick@qq.com"
- git add .
- git commit -m "travis"
- git push -f "https://${MY_TOKEN}@github.com/ladyrick/leetcode.git" master:gh-pages
branches:
  only:
  - master
env:
  global:
    secure: "IbEh2Oml2QutL7O7pbn01FetwFXTgOyx4r22mNfj3UVEUzHxG9DHeAoIagvUop54O8n2BJNilXQQb+i/heaSVHw3rZtUXgLk/+qPmRCRew0d/KCsyGlgfP7U8r3GwBv9HMy8hErrl3Qm4iHF/zFYxmFOZbIQx4UFi8LR8gkgNfph23a9tzK6NiXWRz8TZBK+F1M9D0ygbdx+3isstDFj1FwBuU9dhUop0jsZFbztDY02PrClfoNlPr5ypi5/EjLx3sOHFZMzrLj/nM7tUbKgmvlKGiHGggbGPkSrMCS+6v/1PWP921h5noGpIaCe554zl8Nk7Ge8ASnKZkoiy7AURPhD+7S3jTc3b/68hLi7L8Cpm5RHkH7OozxjL20TwiZ487ja222KHxW95a0c0GQRSAbK1kCNuOeDbr7CixRKqQUsKI0jl3sfxrsL8JsddWypfcosqueclAYnAfPxLPVE7pAH7UCdcHdb5NA4shdVDR7+ltGMRG7qHl+cD4O5S6iU1AHKCpWffIWy8mnF+GMA5Ic9y2bvIDvmACMW504Av6zww8XSuAb5l3zIWAd0rQ5pFlqyzMqqJ16qRU68FXPBJHFLzhAPzTP3cK2cNYDl5Ot6zKzugjPl+7fDiMxPC6WHPuiRRq07S3a3tpam9N0EJZbcjUDx/Hrt2Fg5V25q7bo="